package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountCouponId generated by hbm2java
 */
@Getter
@Setter
@Embeddable
public class AccountCouponId implements java.io.Serializable {

	@Column(name = "coupon_id", nullable = false)
	private int couponId;
	@Column(name = "account_id", nullable = false)
	private int accountId;

	public AccountCouponId() {
	}

	public AccountCouponId(int couponId, int accountId) {
		this.couponId = couponId;
		this.accountId = accountId;
	}
}
