package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import java.util.Objects;

/**
 * AccountCoupon generated by hbm2java
 */
@Getter
@Setter
@Entity
@Table(name = "`account_coupon`")
public class AccountCoupon implements java.io.Serializable {

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "couponId", column = @Column(name = "coupon_id", nullable = false)),
			@AttributeOverride(name = "accountId", column = @Column(name = "account_id", nullable = false)) })
	private AccountCouponId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false, insertable = false, updatable = false)
	private Account account;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_id", nullable = false, insertable = false, updatable = false)
	private Coupon coupon;

	@Column(name = "is_used", nullable = false)
	private boolean isUsed;

	public AccountCoupon() {
	}

	public AccountCoupon(AccountCouponId id, Account account, Coupon coupon, boolean isUsed) {
		this.id = id;
		this.account = account;
		this.coupon = coupon;
		this.isUsed = isUsed;
	}

	@Override
	public int hashCode() {
		return Objects.hash(id);
	}

}
