package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Cart generated by hbm2java
 */
@Getter
@Setter
@Entity
@Table(name = "`cart`")
public class Cart implements java.io.Serializable {

	@Id
	@Column(name = "cart_id")
	private Integer cartId;

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cart_id", referencedColumnName = "id")
	private Account account;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 23)
	private Date createdAt;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 23)
	private Date updatedAt;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cart", cascade = CascadeType.ALL, orphanRemoval = true)
	private Set<CartDetail> cartDetails = new HashSet<CartDetail>(0);

	public Cart() {
	}

	public Cart(Account account, Date createdAt, Date updatedAt) {
		this.account = account;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Cart(Account account, Date createdAt, Date updatedAt, Set<CartDetail> cartDetails) {
		this.account = account;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.cartDetails = cartDetails;
	}

	@Override
	public int hashCode() {
		return Objects.hash(cartId);
	}
}
