package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Category generated by hbm2java
 */

@Getter
@Setter
@Entity
@Table(name = "`catalog`")
public class Catalog implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "catalog_id", unique = true, nullable = false)
	private Integer catalogId;

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "image_id")
	private Image image;

	@Column(name = "description", length = 500, nullable = false)
	private String description;

	@Column(name = "catalog_name", nullable = false)
	private String catalogName;

	@ManyToOne
	@JoinColumn(name = "catalog_parent_id")
	private Catalog parentCatalog;

	@OneToMany(mappedBy = "parentCatalog")
	private List<Catalog> childCatalogs;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalog", cascade = CascadeType.REMOVE, orphanRemoval = true)
	private Set<Product> products = new HashSet<Product>(0);



	public Catalog() {
	}

	public Catalog(Integer catalogId, Image image, String description, String catalogName, Catalog parentCatalog, Set<Product> products) {
		this.catalogId = catalogId;
		this.image = image;
		this.description = description;
		this.catalogName = catalogName;
		this.parentCatalog = parentCatalog;
		this.products = products;
	}
}
