package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import com.project.api.dtos.CouponDTO;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Coupon generated by hbm2java
 */
@Getter
@Setter
@Entity
@Table(name = "`coupon`")
public class Coupon implements Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "coupon_id", unique = true, nullable = false)
	private Integer couponId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_type_id", nullable = false)
	private CouponType couponType;

	@Column(name = "code", nullable = false)
	private String code;

	@Column(name = "discount", nullable = false)
	private int discount;

	@Column(name = "description")
	private String description;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "started_at", length = 23)
	private Date startedAt;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expired_at", length = 23)
	private Date expiredAt;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coupon")
	private Set<Order> orders = new HashSet<Order>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coupon", cascade = CascadeType.REMOVE)
	private Set<AccountCoupon> accountCoupons = new HashSet<AccountCoupon>(0);

	public Coupon() {
	}

	public Coupon(CouponDTO couponDTO) {
		this.couponId = couponDTO.getCouponId();
		this.couponType = new CouponType(couponDTO.getCouponType());
		this.code = couponDTO.getCode();
		this.discount = couponDTO.getDiscount();
		this.description = couponDTO.getDescription();
		this.startedAt = couponDTO.getStartedAt();
		this.expiredAt = couponDTO.getExpiredAt();
	}

	public Coupon(CouponType couponType, String code, int discount, Date startedAt, Date expiredAt) {
		this.couponType = couponType;
		this.code = code;
		this.discount = discount;
		this.startedAt = startedAt;
		this.expiredAt = expiredAt;
	}

	public Coupon(CouponType couponType, String code, int discount, String description, Date startedAt,
			Date expiredAt, Set<Order> orders, Set<AccountCoupon> accountCoupons) {
		this.couponType = couponType;
		this.code = code;
		this.discount = discount;
		this.description = description;
		this.startedAt = startedAt;
		this.expiredAt = expiredAt;
		this.orders = orders;
		this.accountCoupons = accountCoupons;
	}

	@Override
	public int hashCode() {
		return Objects.hash(couponId);
	}
}
