package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import com.project.api.dtos.DistrictDTO;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * District generated by hbm2java
 */

@Getter
@Setter
@Entity
@Table(name = "`district`")
public class District implements Serializable {

	@Id
	@Column(name = "code", unique = true, nullable = false)
	private String code;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "administrative_unit_id")
	private AdministrativeUnit administrativeUnit;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "province_code")
	private Province province;

	@Column(name = "name", nullable = false)
	private String name;

	@Column(name = "name_en")
	private String nameEn;

	@Column(name = "full_name")
	private String fullName;

	@Column(name = "full_name_en")
	private String fullNameEn;

	@Column(name = "code_name")
	private String codeName;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	private Set<Address> addresses = new HashSet<Address>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	private Set<Ward> wards = new HashSet<Ward>(0);

	public District() {
	}

	public District(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public District(DistrictDTO districtDTO) {
		this.code = districtDTO.getCode();
		this.fullName = districtDTO.getFullName();
	}

	public District(String code, AdministrativeUnit administrativeUnit, Province province, String name,
			String nameEn, String fullName, String fullNameEn, String codeName,
			Set<Address> addresses, Set<Ward> wards) {
		this.code = code;
		this.administrativeUnit = administrativeUnit;
		this.province = province;
		this.name = name;
		this.nameEn = nameEn;
		this.fullName = fullName;
		this.fullNameEn = fullNameEn;
		this.codeName = codeName;
		this.addresses = addresses;
		this.wards = wards;
	}

	@Override
	public int hashCode() {
		return Objects.hash(code);
	}

}
