package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */

@Setter
@Getter
@Entity
@Table(name = "`image`")
public class Image implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "image_id", unique = true, nullable = false)
	private Integer imageId;

	@Column(name = "image_url", nullable = false)
	private String imageUrl;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "image")
	private Set<Account> accounts = new HashSet<Account>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "image")
	private Set<ProductVariant> productVariants = new HashSet<ProductVariant>(0);

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "images")
	private Set<Product> products = new HashSet<Product>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "image")
	private Set<Catalog> catalogs = new HashSet<Catalog>(0);

	public Image() {
	}

	public Image(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public Image(String imageUrl, Set<Account> accounts, Set<ProductVariant> productVariants,
			Set<Product> products, Set<Catalog> catalogs) {
		this.imageUrl = imageUrl;
		this.accounts = accounts;
		this.productVariants = productVariants;
		this.products = products;
		this.catalogs = catalogs;
	}

}
