package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import com.project.api.dtos.PaymentMethodDTO;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentMethod generated by hbm2java
 */
@Getter
@Setter
@Entity
@Table(name = "`payment_method`")
public class PaymentMethod implements Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "payment_method_id", unique = true, nullable = false)
	private Integer paymentMethodId;

	@Column(name = "method_name", nullable = false)
	private String methodName;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentMethod")
	private Set<Order> orders = new HashSet<Order>(0);

	public PaymentMethod() {
	}

	public PaymentMethod(String methodName) {
		this.methodName = methodName;
	}

	public PaymentMethod(PaymentMethodDTO paymentMethodDTO) {
		this.paymentMethodId = paymentMethodDTO.getPaymentMethodId();
		this.methodName = paymentMethodDTO.getMethodName();
	}
	public PaymentMethod(String methodName, Set<Order> orders) {
		this.methodName = methodName;
		this.orders = orders;
	}

}
