package com.project.api.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.project.api.dtos.CouponTypeDTO;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * CouponType generated by hbm2java
 */

@Getter
@Setter
@Entity
@Table(name = "`planting_difficulty_level`")
public class PlantingDifficultyLevel implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "planting_difficulty_level_id", unique = true, nullable = false)
	private Integer plantingDifficultyLevelId;

	@Column(name="level", nullable = false)
	private String level;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productSale")
	private Set<Product> products = new HashSet<Product>(0);

	public PlantingDifficultyLevel() {}

	public PlantingDifficultyLevel(String level) {
        this.level = level;
    }
}
