package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductSaleType generated by hbm2java
 */

@Getter
@Setter
@Entity
@Table(name = "`product_sale_type`")
public class  ProductSaleType implements Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_sale_type_id", unique = true, nullable = false)
	private Integer productSaleTypeId;

	@Column(name = "type_name")
	private String typeName;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productSaleType")
	private Set<ProductSale> productSales = new HashSet<ProductSale>(0);

	public ProductSaleType() {
	}

	public ProductSaleType(String typeName, Set<ProductSale> productSales) {
		this.typeName = typeName;
		this.productSales = productSales;
	}

}
