package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ProductColor generated by hbm2java
 */

@Getter
@Setter
@Entity
@Table(name = "`product_size`")
public class ProductSize implements Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_size_id", unique = true, nullable = false)
	private Integer productSizeId;

	@Column(name = "size_name")
	private String sizeName;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productSize")
	private Set<ProductVariant> productVariants = new HashSet<ProductVariant>(0);

	public ProductSize() {
	}

	public ProductSize(String sizeName, Set<ProductVariant> productVariants) {
		this.sizeName  = sizeName;
		this.productVariants = productVariants;
	}

}
