package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import com.project.api.dtos.ProvinceDTO;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Province generated by hbm2java
 */

@Getter
@Setter
@Entity
@Table(name = "`province`")
public class Province implements java.io.Serializable {

	@Id
	@Column(name = "code", unique = true, nullable = false)
	private String code;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "administrative_unit_id")
	private AdministrativeUnit administrativeUnit;

	@Column(name = "name", nullable = false)
	private String name;

	@Column(name = "name_en")
	private String nameEn;

	@Column(name = "full_name", nullable = false)
	private String fullName;

	@Column(name = "full_name_en")
	private String fullNameEn;

	@Column(name = "code_name")
	private String codeName;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "province")
	private Set<District> districts = new HashSet<District>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "province")
	private Set<Address> addresses = new HashSet<Address>(0);

	public Province() {
	}

	public Province(String code, String name, String fullName) {
		this.code = code;
		this.name = name;
		this.fullName = fullName;
	}

	public Province(String code, AdministrativeUnit administrativeUnit, String name, String nameEn,
			String fullName, String fullNameEn, String codeName,
			Set<District> districts, Set<Address> addresses) {
		this.code = code;
		this.administrativeUnit = administrativeUnit;
		this.name = name;
		this.nameEn = nameEn;
		this.fullName = fullName;
		this.fullNameEn = fullNameEn;
		this.codeName = codeName;
		this.districts = districts;
		this.addresses = addresses;
	}

	public Province(ProvinceDTO provinceDTO) {
		this.code = provinceDTO.getCode();
		this.fullName = provinceDTO.getFullName();
	}

	@Override
	public int hashCode() {
		return Objects.hash(code);
	}

}
