package com.project.api.entities;
// Generated Jul 25, 2023, 8:08:56 PM by Hibernate Tools 4.3.6.Final

import com.project.api.dtos.WardDTO;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ward generated by hbm2java
 */
@Getter
@Setter
@Entity
@Table(name = "`ward`")
public class Ward implements Serializable {

	@Id
	@Column(name = "code", unique = true, nullable = false)
	private String code;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "administrative_unit_id")
	private AdministrativeUnit administrativeUnit;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "district_code")
	private District district;

	@Column(name = "name", nullable = false)
	private String name;

	@Column(name = "name_en")
	private String nameEn;

	@Column(name = "full_name")
	private String fullName;

	@Column(name = "full_name_en")
	private String fullNameEn;

	@Column(name = "code_name")
	private String codeName;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ward")
	private Set<Address> addresses = new HashSet<Address>(0);

	public Ward() {
	}

	public Ward(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public Ward(WardDTO wardDTO) {
		this.code = wardDTO.getCode();
		this.fullName = wardDTO.getFullName();
	}

	public Ward(String code, AdministrativeUnit administrativeUnit, District district, String name,
			String nameEn, String fullName, String fullNameEn, String codeName,
			Set<Address> addresses) {
		this.code = code;
		this.administrativeUnit = administrativeUnit;
		this.district = district;
		this.name = name;
		this.nameEn = nameEn;
		this.fullName = fullName;
		this.fullNameEn = fullNameEn;
		this.codeName = codeName;
		this.addresses = addresses;
	}

	@Override
	public int hashCode() {
		return Objects.hash(code);
	}

}
